swagger: "2.0"
info:
  version: "2.0"
  title: 'Example API'
  license:
    name: Proprietary
    url: 'http://example.com/contact-us/'
host: api.example.com
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /thing/aspect:
    summary: 'Aspect of Thing'
    description: 'Handles requests involving an aspect of a thing'
    post:
      description: "Upload a thing's aspect"
      operationId: ThingAspectPost
      responses:
        200:
          $ref: '#/components/responses/apiResp'
    get:
      description: "Get a thing's aspect"
      operationId: ThingAspectGet
      responses:
        200:
          $ref: '#/components/responses/apiResp'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: robothive_api_key
      in: header
      description: "API Key for RobotHive"
    basic:
      type: http
      scheme: basic
      description: "Basic HTTP Authentication"

  responses:
    apiResp:
      description: Standard API Response for successful
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/VeryComplexType'
